### ISSUE TITLE
training the language adapters in the MAD-X paper 

### ISSUE THREAD

**Issue by dorost1234** [Adapter-Hub/adapter-transformers#125] opened 2021-02-28 09:49 UTC
Hi
I would need to train language adapters as done in MAD-X paper, I have downloaded wikipedia data, but these are very large-scale data and so far I did not managed to train them, I was wondering if you could share with me the script that you managed to train the language adapters, thank you very much in advance.

**Comment by dorost1234** [comment] 2021-02-28 09:50
@calpt @fteufel  thank you so much for your help.

**Comment by dorost1234** [comment] 2021-03-02 19:33
I am getting a lot of memory issues and not sure how to train it, greatly appreciate sharing script of training language adapters done in your work with me, thanks a lot

**Comment by JoPfeiff** [comment] 2021-03-02 20:07
The language modeling script we have used in the past has been pushed into legacy: [link](https://github.com/Adapter-Hub/adapter-transformers/blob/master/examples/contrib/legacy/run_language_modeling.py)
Is this the script you have been using until now?

We will add adapter support to the new language modeling scripts ASAP.

Where are you getting memory issues? RAM or VRAM?

**Comment by dorost1234** [comment] 2021-03-02 20:11
Hi, thank you very much Jonas first for coming back to me, I am adding adapters as done in tutorial and then use the link you mentioned, then I try to run it with this dataset from huggingface library:

datasets.load_dataset("wikipedia", "20200501.aa")

and getting os memory issues, I appreciate also having a look into the bug I opened for the memory issues: https://github.com/huggingface/datasets/issues/1977

OSError: Memory mapping file failed: Cannot allocate memory

not sure how to train it, and greatly appreciate your help., thanks a lot.

**Comment by dorost1234** [comment] 2021-03-02 20:16
It seems one need apache-beam to train models on these datasets, sorry I have never used it, did you use it to be able to train your models on these large-scale datasets? thank you very much.

**Comment by JoPfeiff** [comment] 2021-03-02 20:16
hm, this doesn't seem to be a caused by the adapter-transformers repo.
It looks like you don't have enough RAM:
https://github.com/prlz77/ResNeXt.pytorch/issues/5

**Comment by dorost1234** [comment] 2021-03-02 20:21
Hi Jonas,
thanks for your help, could you tell me how much RAM I need to have to be able to train language adapters? and did you do it on a single machine? thanks for the information, this helps me a lot.

**Comment by JoPfeiff** [comment] 2021-03-02 20:25
It really depends on the language and its respective corpus size. The english wiki is quite large. 
However when loading the dataset you might just early stop at N documents/lines. That way you can test your script and see how much fits in your memory. 
I haven't used the `datasets` version of wiki, but crawled and preprocessed the respective wiki dumps myself, so I am not sure how this would work in your case.

**Comment by dorost1234** [comment] 2021-03-02 20:57
Hi Jonas,
thanks, do you mind sharing the machine specification you used for the
largest dataset used in your work? This helps me a lot to know the machine
specification used in MAD-X work.
So you mean to subsample also the datasets to be able to partly load them?

thanks a lot for all help.

**Comment by JoPfeiff** [comment] 2021-03-02 20:59
primarily I use a DGX-2 server.
However, I have also trained language adapters on my home machine which has 64gb RAM and a Titan X GPU.

**Comment by dorost1234** [comment] 2021-03-02 21:02
Hi Jonas,
So you trained them on 16 V100 GPUs? I was thinking this is done on 1 GPU,
could you please confirm the number of GPUs used for the training?
thanks a lot

**Comment by JoPfeiff** [comment] 2021-03-02 21:03
1 GPU on the server.
As mentioned, this also works fine on 12gb gpus. You just have to leverage gradient accumulation

**Comment by calpt** [comment] 2021-05-03 10:05
Closing for now, please reopen if there still is something unclear.

**Closed by calpt** 2021-05-03 10:05 UTC
Labels: question
